### ISSUE TITLE
not zipping folders on weekends

### ISSUE THREAD

**Issue by ilyas-shah** [sole/node-zip-folder#11]
I have put this script in a scheduler which runs everyday at a particular time and zip a folder named as the date of that particular day, i found that on weekends this script is not able to zip that folder although folder is already there. Any suggestions?

**Comment by ktshikotshi** [comment]
even the script needs a break, try talking to the union representative

**Comment by msamprz** [comment]
@ilyas-shah have you found a solution for this? /s

**Comment by ilyas-shah** [comment]
No, i used a different module...

**Comment by ghost** [comment]
Doesn't make any sense that it won't work on specific days, sounds like an issue with your scheduler.

**Comment by ilyas-shah** [comment]
anyways, i no longer work on that project where i had this problem, therefore closing the issue.  Bye!
